### ISSUE TITLE
Changes in Directory.Build.props not detected

### ISSUE THREAD

**Issue by garcipat** [leonardochaia/dotnet-affected#42]
We work with a Directory.Build.Props file that adds some of the Tags to all projects in the same folder. When this file changes, dotnet-affected does not detect the change, even if it can affect the whole project (for example changing .net version)

Example:
```csharp
<Project>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Product>My Product</Product>
  </PropertyGroup>
</Project>
```

I dont know how that could be detected either.

**Comment by leonardochaia** [comment]
Hi @garcipat! Thanks for reaching out.

Yeah, unfortunately, that is [one of the caveats](https://github.com/leonardochaia/dotnet-affected#caveats) in the readme.

It would be great if we could support it; my team also uses `Directory.Build.props` to customize a lot of stuff.

For props files that are "global", meaning they affect all projects it is not hard: run git diff against those files and if there's any changes trigger a complete build (which can be done using wildcards + Traversal SDK file).

For props files that are in a directory recursively affecting all projects down the hierarchy I am not sure how we could implement it.

I'm gonna leave this open since this is an actual issue, even if it is a "known issue". Perhaps someone can think something out :+1:

**Comment by garcipat** [comment]
Wel it means if you have a prop file and its changed, you need to all all project files down the hierarchy to the Travel SDK file I guess.

**Comment by leonardochaia** [comment]
Hi @garcipat. `v3.0.0-preview-1` has been released on nuget. Would you give it a go and report back?

It should detect `Directory.Package.props` properly.

Have a great weekend!
Leo

**Comment by garcipat** [comment]
Yes I have seen it. Im very excited. I wanted to check it out. Will do that
next week when I get back to work.

Leonardo Chaia ***@***.***> schrieb am Sa., 30. Juli 2022,
13:42:
